DROP USER parkchanho CASCADE;

CREATE USER parkchanho IDENTIFIED BY parkchanho DEFAULT TABLESPACE USERS;
GRANT CONNECT, RESOURCE TO parkchanho;

CREATE SEQUENCE PARKCHANHO.FLOWERS_FLOWERNUM_SEQ
INCREMENT BY 1 
START WITH 1 
MINVALUE 1 
NOCACHE
NOCYCLE;

CREATE SEQUENCE PARKCHANHO.CARTS_CARTNUM_SEQ
INCREMENT BY 1 
START WITH 1 
MINVALUE 1 
NOCACHE
NOCYCLE;

CREATE SEQUENCE PARKCHANHO.ORDERS_ORDERNUM_SEQ
INCREMENT BY 1 
START WITH 1
MINVALUE 1 
NOCACHE
NOCYCLE;

CREATE SEQUENCE PARKCHANHO.REVIEWS_REVIEWNUM_SEQ
INCREMENT BY 1 
START WITH 1 
MINVALUE 1 
NOCACHE
NOCYCLE;

CREATE SEQUENCE PARKCHANHO.NOTICES_NOTICENUM_SEQ
INCREMENT BY 1 
START WITH 1 
MINVALUE 1 
NOCACHE
NOCYCLE;

CREATE TABLE PARKCHANHO.USERS(
USER_ID VARCHAR2(10) CONSTRAINT USER_ID_PK PRIMARY KEY,
USER_PW VARCHAR2(20) CONSTRAINT USER_PW_NN NOT NULL,
USER_NAME VARCHAR2(20) CONSTRAINT USER_NAME_NN NOT NULL,
BIRTHDAY DATE CONSTRAINT USER_BIRTHDAY_NN NOT NULL,
EMAIL VARCHAR2(50) CONSTRAINT USER_EMAIL_NN NOT NULL,
CONTACT_NUM VARCHAR2(15) CONSTRAINT USER_CONTACT_NUM_NN NOT NULL,
POSTCODE VARCHAR2(5),
ADDR VARCHAR2(100),
DETAIL_ADDR VARCHAR2(100)
);

CREATE TABLE PARKCHANHO.FLOWERS(
FLOWER_NUM NUMBER(3) CONSTRAINT FLOWER_FLOWERNUM_PK PRIMARY KEY,
FLOWER_NAME VARCHAR2(50) CONSTRAINT FLOWER_FLOWERNAME_NN NOT NULL,
PRICE NUMBER(10) CONSTRAINT FLOWER_PRICE_NN NOT NULL,
AMOUNT NUMBER(10) ,
KIND VARCHAR2(100) CONSTRAINT FLOWER_KIND_NN NOT NULL,
FLOWER_CATEGORY VARCHAR2(100) CONSTRAINT FLOWER_FLOWERCATEGORY_NN NOT NULL,
FLOWER_IMGFILE_NAME VARCHAR2(100),
DETAIL VARCHAR2(100),
REGDATE DATE DEFAULT SYSDATE CONSTRAINT FLOWER_REGDATE_NN NOT NULL
);

CREATE TABLE PARKCHANHO.CARTS (
CART_NUM NUMBER(3) CONSTRAINT CARTS_CARTNUM_PK PRIMARY KEY,
AMOUNT NUMBER(3) CONSTRAINT CARTS_AMOUNT_NN NOT NULL,
USER_ID VARCHAR2(10), CONSTRAINT CARTS_USERID_FK FOREIGN KEY(USER_ID)
       REFERENCES PARKCHANHO.USERS(USER_ID),
FLOWER_NUM NUMBER(3), CONSTRAINT CARTS_FLOWERNUM_FK FOREIGN KEY(FLOWER_NUM)
       REFERENCES PARKCHANHO.FLOWERS(FLOWER_NUM)
);

CREATE TABLE PARKCHANHO.ORDERS (
ORDER_NUM NUMBER(15) CONSTRAINT ORDERS_ORDERNUM_PK PRIMARY KEY,
AMOUNT NUMBER(10) CONSTRAINT ORDERS_AMOUNT_NN NOT NULL,
PRICE NUMBER(10) CONSTRAINT ORDERS_PRICE_NN NOT NULL,
REC_NAME VARCHAR2(10) CONSTRAINT ORDERS_RECNAME_NN NOT NULL,
REC_CONTACT_NUM VARCHAR2(15) CONSTRAINT ORDERS_RECCONTACTNUM_NN NOT NULL,
REC_POSTCODE VARCHAR2(5) CONSTRAINT ORDERS_RECPOSTCODE_NN NOT NULL,
REC_ADDR VARCHAR2(100) CONSTRAINT ORDERS_RECADDR_NN NOT NULL,
REC_DETAIL_ADDR VARCHAR2(100) CONSTRAINT ORDERS_RECDETAILADDR_NN NOT NULL,
HOPE_DELI_DATE DATE CONSTRAINT ORDERS_HOPEDELIDATE_NN NOT NULL,
REQUEST VARCHAR2(100),
PAYMENT VARCHAR2(100) CONSTRAINT ORDERS_PAYMENT_NN NOT NULL,
DELI_FEE NUMBER(10) DEFAULT 5000,
DELI_STATE VARCHAR2(50) DEFAULT '상품 준비중',
USER_ID VARCHAR2(10), CONSTRAINT ORDERS_USERID_FK FOREIGN KEY(USER_ID)
       REFERENCES  PARKCHANHO.USERS(USER_ID),
FLOWER_NUM NUMBER(3), CONSTRAINT ORDERS_FLOWERNUM_FK FOREIGN KEY(FLOWER_NUM)
       REFERENCES  PARKCHANHO.FLOWERS(FLOWER_NUM)
); 

CREATE TABLE PARKCHANHO.REVIEWS (
REVIEW_NUM NUMBER(3) CONSTRAINT REVIEW_REVIEWNUM_PK PRIMARY KEY,
TITLE VARCHAR2(30) CONSTRAINT REVIEW_TITLE_NN NOT NULL,
CONTENT VARCHAR2(1000), 
REGDATE DATE CONSTRAINT REVIEW_REGDATE_NN NOT NULL,
USER_ID VARCHAR2(10),
CONSTRAINT REVIEW_USER_ID_FK FOREIGN KEY(USER_ID)
    REFERENCES PARKCHANHO.USERS(USER_ID)
);

CREATE TABLE PARKCHANHO.NOTICES (
NOTICE_NUM NUMBER(3) CONSTRAINT NOTICE_NOTICE_NUM_PK PRIMARY KEY,
TITLE VARCHAR2(30) CONSTRAINT NOTICE_TITLE_NN NOT NULL,
CONTENT VARCHAR2(1000) CONSTRAINT NOTICE_CONTENT_NN NOT NULL, 
REGDATE DATE CONSTRAINT NOTICE_REGDATE_NN NOT NULL);

INSERT INTO PARKCHANHO.USERS (
    USER_ID, USER_PW, USER_NAME, BIRTHDAY, EMAIL, CONTACT_NUM, POSTCODE, ADDR, DETAIL_ADDR) 
    VALUES (
    'user', 'user', '박찬호', TO_DATE('1991-03-01', 'YYYY-MM-DD'), 'qwer123@gmail.com', '01012340000', '10412', '경기도 고양시 일산동구 마두동', '마두법조 빌딩 9층');

INSERT INTO PARKCHANHO.USERS (
    USER_ID, USER_PW, USER_NAME, BIRTHDAY, EMAIL, CONTACT_NUM, POSTCODE, ADDR, DETAIL_ADDR) 
    VALUES ('admin', 'admin', '관리자', TO_DATE('1991-03-01', 'YYYY-MM-DD'), 'qwer456@gmail.com', '01012345678', '10412', '경기도 고양시 일산동구 마두동', '마두법조 빌딩 9층');
    
commit;